# Generated by Django 6.1 on 2026-08-31 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='drink', max_length=10),
        ),
    ]
