# Generated by Django 6.1 on 2026-09-06 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0002_order_staff_orderitem_order_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
