# Generated by Django 6.1 on 2026-09-08 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0003_alter_staff_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
