# Generated by Django 6.1 on 2026-09-13 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0005_product_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
