# Generated by Django 6.1 on 2026-10-10 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0007_category_product_allergy_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='photo',
            field=models.ImageField(unique=True, upload_to=''),
        ),
    ]
